language: ruby
bundler_args: --without debug
sudo: false
before_install: gem install -v '~> 1.10' bundler
script: "bundle exec rspec spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - 2.1.6
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head

